Exception thrown: {
   "_exception" : "Foo",
   "params" : []
}
